name = "str-erp-system"
main = "worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
AUTH_SHEET_ID = "1uM237XywBb0lFa9wavSP-rxNEOYUQldJp7AnLX09uM8"
PRODUCT_SHEET_ID = "1pCuUFizx8K2VTjMGGXB4MYfVJQndIFseky_gKuzApPg"
ACCOUNT_SHEET_ID = "10jTkGZMirCg8Pb3FsRGP_6LLiDbl8K4rmkZ31tCNSwY"
