name = "str-erp-system"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[vars]
AUTH_SHEET_ID = "1uM237XywBb0lFa9wavSP-rxNEOYUQldJp7AnLX09uM8"
PRODUCT_SHEET_ID = "1pCuUFizx8K2VTjMGGXB4MYfVJQndIFseky_gKuzApPg"
ACCOUNT_SHEET_ID = "10jTkGZMirCg8Pb3FsRGP_6LLiDbl8K4rmkZ31tCNSwY"

# Note: Set SERVICE_ACCOUNT_KEY via:
# wrangler pages secret put SERVICE_ACCOUNT_KEY
